"""add teams and training_teams

Revision ID: 243dd78437d6
Revises: 2dda5f0246d8
Create Date: 2026-07-23 18:19:29.217017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243dd78437d6'
down_revision: Union[str, Sequence[str], None] = '2dda5f0246d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_teams',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.PrimaryKeyConstraint('training_id', 'team_id')
    )
    op.add_column('players', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_players_team_id", 'players', 'teams', ['team_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_players_team_id", 'players', type_='foreignkey')
    op.drop_column('players', 'team_id')
    op.drop_table('training_teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
